# Generated by Django 4.0.3 on 2022-04-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Тема')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер задачи')),
                ('short_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('description', models.TextField(verbose_name='Условие задачи')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('correct_answer', models.CharField(max_length=250, verbose_name='Правильный ответ')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.theme', verbose_name='Тема')),
            ],
            options={
                'ordering': ['theme', 'number'],
            },
        ),
    ]
