# Generated by Django 4.0.3 on 2022-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='solution_example',
            field=models.TextField(blank=True, null=True, verbose_name='Способы решения'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
