# Generated by Django 4.0.3 on 2022-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='id',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Порядковый номер задачи'),
        ),
    ]
