# Generated by Django 4.0.3 on 2022-04-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_exercise_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер задачи'),
        ),
    ]
